//////////////////////////////////////////////////////////////////////////
// Criacao...........: 06/2014
// Sistema...........: Loja Virtual
// Analistas.........: Marilene Esquiavoni & Denny Paulista Azevedo Filho
// Desenvolvedores...: Marilene Esquiavoni & Denny Paulista Azevedo Filho
// Copyright.........: Marilene Esquiavoni & Denny Paulista Azevedo Filho
//////////////////////////////////////////////////////////////////////////

// <auto-generated />
namespace MD.LojaVirtual.Dominio.Migrations
{
  using System.CodeDom.Compiler;
  using System.Data.Entity.Migrations;
  using System.Data.Entity.Migrations.Infrastructure;
  using System.Resources;

  [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
  public sealed partial class AddPedido : IMigrationMetadata
  {
    private readonly ResourceManager Resources = new ResourceManager(typeof(AddPedido));

    string IMigrationMetadata.Id
    {
      get { return "201611202151298_AddPedido"; }
    }

    string IMigrationMetadata.Source
    {
      get { return null; }
    }

    string IMigrationMetadata.Target
    {
      get { return Resources.GetString("Target"); }
    }
  }
}
